version: '3.8'
services:
  web:
    container_name: django_dev
    image: "django-docker:dev"
    build:
      target: development_build
      context: .
      cache_from:
        - "django-docker:dev"
        - "django-docker:latest"
        - "*"
      args:
        DJANGO_ENV: development
    volumes:
      - .:/project
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres_dev
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
